general:
  name: iotdscreator
  timeout: 600
scenario_verifier:
  name: scenario_verifier
  preset_directory: nodes/presets
  timeout: 600
network_abstractor:
  name: network_abstractor
physical_node_mapper:
  name: physical_node_mapper
virtual_network_constructor:
  name: virtual_network_constructor
  host_info_manager:
    name: default
    port: 10200
application_installer:
  name: application_installer
  application_cache:
    name: default
    port: 10201
    cache_directory: ~/iotdscreator-cache
attack_scenario_executor:
  name: attack_scenario_executor
data_labeler:
  name: data_labeler
  zitter: 0.5
feature_extractor:
  name: feature_extractor
  features:
    packet:
      is_ack: true
      destination_mac_address: true
      acknowledge_number: true
      is_rst: true
      is_cwr: true
      is_fin: true
      total_ip_packet_length: true
      window_size: true
      network_protocol: true
      is_psh: true
      is_syn: true
      is_urg: true
      transport_protocol: true
      ttl: true
      ip_identifier: true
      sequence_number: true
      is_ece: true
      source_mac_address: true
    flow:
      flow_iat_std: true
      forward_packet_length_max: true
      total_bhlen: true
      flow_protocol: true
      bpkts_per_second: true
      flow_iat_total: true
      forward_iat_max: true
      flow_iat_mean: true
      forward_packet_length_mean: true
      fpkts_per_second: true
      flow_packets_per_second: true
      forward_iat_total: true
      forward_packet_length_std: true
      total_fhlen: true
      forward_iat_min: true
      backward_iat_std: true
      backward_packet_length_mean: true
      backward_iat_total: true
      total_forward_packets: true
      backward_packet_length_std: true
      backward_packet_length_min: true
      flow_ece: true
      forward_packet_length_min: true
      flow_cwr: true
      flow_rst: true
      backward_iat_mean: true
      flow_urg: true
      flow_psh: true
      forward_iat_std: true
      total_length_of_forward_packets: true
      backward_packet_length_max: true
      forward_iat_mean: true
      total_length_of_backward_packets: true
      total_backward_packets: true
      flow_fin: true
      flow_ack: true
      flow_syn: true
      backward_iat_min: true
      flow_iat_min: true
      backward_iat_max: true
      flow_iat_max: true
    host:
      cpu_running_time_on_user_mode: true
      total_swap_space_megabytes: true
      filesystem_metadata: true
      page_cache_megabytes: true
      current_vm_space_megabytes: true
      number_of_received_icmp_datagrams: true
      number_of_retransmission: true
      disk_busy_time: true
      number_of_active_tcp_open: true
      cpu_utilization_on_interrupt_handling: true
      total_memory_megabytes: true
      sleeping_uninterruptible: true
      number_of_received_udp_datagrams: true
      number_of_context_switching: true
      number_of_passive_tcp_open: true
      cpu_load_average_per_15_minutes: true
      number_of_transmitted_tcp_segments: true
      cpu_waiting_time_percentage: true
      number_of_transmitted_icmp_datagrams: true
      number_of_open_processes: true
      read_request_throughput: true
      total_free_memory_megabytes: true
      cpu_load_average_per_minute: true
      number_of_running_threads: true
      free_swap_space_megabytes: true
      clone_system_call: true
      number_of_exit_processes: true
      maximum_vm_space_megabytes: true
      cpu_load_average_per_5_minutes: true
      cpu_running_time_on_system_mode: true
      cpu_idle_time_percentage: true
      number_of_zombie_processes: true
      number_of_transmitted_udp_datagrams: true
      number_of_received_tcp_segments: true
      kernel_malloc: true
      cpu_stolen_time_percentage: true
      cpu_utilization_on_kernel_mode: true
      write_request_throughput: true
      cpu_utilization_on_user_mode: true
      number_of_interrupt: true
    transition:
      mean_number_of_received_udp_datagrams: true
      min_number_of_transmitted_tcp_segments: true
      max_number_of_transmitted_icmp_datagrams: true
      max_number_of_received_udp_datagrams: true
      min_kernel_malloc: true
      max_total_swap_space_megabytes: true
      min_number_of_transmitted_icmp_datagrams: true
      max_number_of_transmitted_udp_datagrams: true
      min_number_of_transmitted_udp_datagrams: true
      mean_number_of_transmitted_icmp_datagrams: true
      max_number_of_received_tcp_segments: true
      mean_cpu_utilization_on_user_mode: true
      mean_number_of_received_tcp_segments: true
      mean_sleeping_uninterruptible: true
      min_total_free_memory_megabytes: true
      min_cpu_idle_time_percentage: true
      max_total_free_memory_megabytes: true
      min_sleeping_uninterruptible: true
      min_number_of_zombie_processes: true
      mean_cpu_utilization_on_kernel_mode: true
      min_total_swap_space_megabytes: true
      mean_number_of_transmitted_udp_datagrams: true
      mean_cpu_idle_time_percentage: true
      max_number_of_open_processes: true
      min_write_request_throughput: true
      min_read_request_throughput: true
      mean_cpu_running_time_on_user_mode: true
      min_cpu_running_time_on_user_mode: true
      max_sleeping_uninterruptible: true
      max_cpu_utilization_on_user_mode: true
      max_number_of_exit_processes: true
      max_number_of_running_threads: true
      max_cpu_idle_time_percentage: true
      max_write_request_throughput: true
      min_cpu_utilization_on_kernel_mode: true
      mean_number_of_received_icmp_datagrams: true
      max_read_request_throughput: true
      mean_total_memory_megabytes: true
      max_number_of_received_icmp_datagrams: true
      mean_number_of_zombie_processes: true
      min_number_of_running_threads: true
      min_total_memory_megabytes: true
      mean_number_of_transmitted_tcp_segments: true
      max_cpu_running_time_on_user_mode: true
      min_cpu_running_time_on_system_mode: true
      min_cpu_utilization_on_user_mode: true
      max_cpu_running_time_on_system_mode: true
      max_cpu_utilization_on_kernel_mode: true
      mean_number_of_exit_processes: true
      mean_total_swap_space_megabytes: true
      mean_number_of_open_processes: true
      min_number_of_received_udp_datagrams: true
      mean_kernel_malloc: true
      mean_read_request_throughput: true
      max_number_of_transmitted_tcp_segments: true
      max_number_of_zombie_processes: true
      mean_cpu_running_time_on_system_mode: true
      min_number_of_received_tcp_segments: true
      min_number_of_received_icmp_datagrams: true
      min_number_of_exit_processes: true
      max_kernel_malloc: true
      mean_total_free_memory_megabytes: true
      max_total_memory_megabytes: true
      mean_write_request_throughput: true
      mean_number_of_running_threads: true
      min_number_of_open_processes: true
  network_window_manager:
    name: network_window_manager
    window_length: 100000
    sliding_window: true
    sliding_window_interval: 10000
  host_window_manager:
    name: host_window_manager
    window_length: 100000
    sliding_window: true
    sliding_window_interval: 10000
